[viewer]
    Title = "叶培宇的个人博客"
    Description = "长得很帅"
    Logo = "/resource/images/log.png"
    Navigation = ["首页","/", "GO语言","/golang", "归档","/pigeonhole", "关于","/about"]
    Bilibili = "https://space.bilibili.com/500391864?spm_id_from=333.1007.0.0"
    Zhihu = "https://www.zhihu.com/people/gu-huo-84-19"
    Avatar = "/resource/images/image.jpg"
    UserName = "叶培宇"
    UserDesc = "长得非常帅的软件工程师"
[system]
    CdnURL = "https://static.mszlu.com/goblog/es6/md-assets"
    QiniuAccessKey = "替换自己的"
    QiniuSecretKey = "替换自己的"
    Valine = true
    ValineAppid = "oOAKEPSW31bmcc4oTHtCyCce-gzGzoHsz"
    ValineAppkey = "aQExxGhgr5MQWxEL619T08OQ"
    ValineServerURL = "https://ooakepsw.lc-cn-n1-shared.com"